import { BadgeStyle } from "../enums/BadgeStyle";
import { ItemsCollection } from "../modules/ItemsCollection";
import { ListItem } from "../modules/ListItem";
import { ResText } from "../modules/ResText";
import { Sprite } from "../modules/Sprite";
import { UIMenuItem } from "./UIMenuItem";
export declare class UIMenuListItem extends UIMenuItem {
    protected _itemText: ResText;
    protected _arrowLeft: Sprite;
    protected _arrowRight: Sprite;
    private _holdTime;
    private currOffset;
    private collection;
    Collection: ListItem[];
    SelectedItem: ListItem;
    readonly SelectedValue: any;
    ScrollingEnabled: boolean;
    HoldTimeBeforeScroll: number;
    private readonly OnListChanged;
    readonly ListChanged: import("../utils/LiteEvent").ILiteEvent;
    protected _index: number;
    Index: number;
    constructor(text: string, description?: string, collection?: ItemsCollection, startIndex?: number);
    setCollection(collection: ItemsCollection): void;
    setCollectionItem(index: number, item: ListItem | string, resetSelection?: boolean): void;
    SetVerticalPosition(y: number): void;
    SetRightLabel(text: string): this;
    SetRightBadge(badge: BadgeStyle): this;
    Draw(): void;
}
